### ISSUE TITLE
Here is updated verison!

### ISSUE THREAD

**Issue by GameFusionNetWork** [FlipperPlz/PakExplorer#11]
I am excited to announce the release of the updated version of our app! This new version comes with significant enhancements designed to improve your experience and productivity. Here are the key updates:

Support for Large Files: Our updated app now allows you to upload, download, and manage large files seamlessly. Say goodbye to size limitations and enjoy the freedom to handle larger data effortlessly.

Comprehensive File Management: You can now access and manage every file within a PAK file. This means greater flexibility and control over your archived files, making it easier to handle complex data structures and projects.

However, we are aware of a current limitation regarding paths within .xob and .ett files. Our team is actively working on a fix for this issue. In the meantime, you can manually adjust these paths using Workbench.

We believe these improvements will greatly benefit your workflow and enhance the overall functionality of the app. As always, we appreciate your feedback and suggestions, which help us continue to improve and innovate.

To get started with the updated version, please visit. For any questions or support, feel free to reach out to our support team on discord : https://discord.gg/YGu26VTR

Download here: https://drive.google.com/file/d/1hpOsP8lro7BbcvI3sbTehY8g71sOe1vh/view?usp=sharing
Discord : https://discord.gg/YGu26VTR

**Comment by FlipperPlz** [comment]
AHHHH I did not see it apologies, good luck with your fork happy the codebase found you well!
